In [576]:
# import modules
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from sklearn.model_selection import GroupShuffleSplit
from scipy import stats
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import optimizers
from datetime import datetime
from kerastuner.tuners import RandomSearch
import tensorflow_addons as tfa
from keras.utils import to_categorical 
from keras.regularizers import l2
import os



r_seed = 42

from pathlib import Path
WORKDIR = str(Path.cwd().parent) + '/'  # raiz do repositório
np.random.seed(r_seed)
tf.random.set_seed(r_seed)
data_hora= datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
LOG_DIR = WORKDIR + "/logs/"+data_hora

In [577]:
date = datetime.now()
date = date.strftime("%d/%m/%Y_%H:%M")
arq = datetime.now()
arq = arq.strftime("%d_%m_%Y_%H_%M")

In [578]:
def combine_csv_data(directory):
    # Specify the directory containing the TXT files

    # Create an empty list to store the DataFrames
    dfs = []

    # Iterate through the TXT files in the directory
    for filename in os.listdir(directory):
        if filename.endswith(".txt"):
            # Read the CSV data from the TXT file, assuming no header row
            df = pd.read_csv(os.path.join(directory, filename), header=None)

            # Append the DataFrame to the list
            dfs.append(df)

    # Concatenate the DataFrames into a single DataFrame
    combined_df = pd.concat(dfs, ignore_index=True)

    # Print the combined DataFrame
    return combined_df

In [579]:
def equalize_dataframe_sizes(df1, df2):
    """Equalizes the sizes of two DataFrames by dropping rows from the larger one.

    Args:
        df1 (pd.DataFrame): The first DataFrame.
        df2 (pd.DataFrame): The second DataFrame.

    Returns:
        tuple: A tuple containing the equalized DataFrames (df1, df2).

    Raises:
        ValueError: If both DataFrames have the same size.
    """

    if df1.shape[0] == df2.shape[0]:
        raise ValueError("Both DataFrames already have the same size.")

    larger_df, smaller_df = (df1, df2) if df1.shape[0] > df2.shape[0] else (df2, df1)

    # Drop rows from the larger DataFrame to match the smaller one
    larger_df = larger_df.iloc[: smaller_df.shape[0], :]

    return larger_df, smaller_df

# Example usage
#df1 = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': ['a', 'b', 'c', 'd', 'e']})
#df2 = pd.DataFrame({'A': [10, 20, 30], 'B': ['x', 'y', 'z']})

''' try:
    df1_equal, df2_equal = equalize_dataframe_sizes(df1.copy(), df2.copy())
    #print("Equalized DataFrames:")
    #print(df1_equal)
    #print(df2_equal)
except ValueError as e:
    print(e) '''

' try:\n    df1_equal, df2_equal = equalize_dataframe_sizes(df1.copy(), df2.copy())\n    #print("Equalized DataFrames:")\n    #print(df1_equal)\n    #print(df2_equal)\nexcept ValueError as e:\n    print(e) '

In [580]:
def custom_concat(df1, df2):
    """
    Concatenates two DataFrames with the same column names, considering specific conditions.

    Args:
        df1 (pd.DataFrame): The first DataFrame.
        df2 (pd.DataFrame): The second DataFrame.

    Returns:
        pd.DataFrame: The concatenated DataFrame.
    """

    result_df = pd.DataFrame()

    # Create groups based on unique combinations of X and Y values
    groups_df1 = df1.groupby(['pessoa_gyro','atividade_gyro'])
    groups_df2 = df2.groupby(['pessoa', 'atividade'])

    # Iterate over groups from both DataFrames simultaneously
    for (x, y), group1 in groups_df1:
        #print(x,y)
        #if (x,y) in [(1637, 'C'),(1638, 'H'),(1638, 'O'),(1640, 'C'),(1640, 'E')]:
        #    continue
        #else:
        group2 = groups_df2.get_group((x, y))
        '''  group1_has_nan = group1.isnull().sum().sum() > 0
        group2_has_nan = group2.isnull().sum().sum() > 0
        if group1_has_nan == True:
                print(group1.isnull().sum().sum())
                print (group1)
                break
        if group2_has_nan == True:
                print(group2.isnull().sum().sum())
                print (group2)
                break '''
        
        if group2 is not None:  # Check if corresponding group exists in df2
            if group1.shape[0] != group2.shape[0]:
                #print(group1)
                #print(group1)

                group1, group2 = equalize_dataframe_sizes(group1.copy(), group2.copy())
                #print(f"+++++++++++++++++++++++++++++++++Imprimindo shape grupo 1 e 2 :{group1_equal.shape[0]} - {group2_equal.shape[0]}" )
                #print(f"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Imprimindo dados grupo 1 :{group1_equal}" )
                #print("---------------------------------------------")
                #print(f"####################################Imprimindo dados grupo 2 :{group2_equal}" )
            #print(f"+++++++++++++++++++++++++++++++++Imprimindo shape grupo 1 e 2 :{group1_equal.shape[0]} - {group2_equal.shape[0]}" )
            #print(f"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Imprimindo dados grupo 1 :{group1_equal}" )
            #print("---------------------------------------------")
            #print(f"####################################Imprimindo dados grupo 2 :{group2_equal}" ) 
            group1 = group1.reset_index(drop=True) 
            group2= group2.reset_index(drop=True)  
            df_concat_group1_group2 = pd.concat([group1, group2], axis=1)
            #print(df_concat_group1_group2)
            df_concat_group1_group2 = df_concat_group1_group2.dropna()            
            #print(df_concat_group1_group2)
            has_nan = df_concat_group1_group2.isnull().sum().sum() > 0
            if has_nan == True:
                print (f"**************************** Imprimindo concat co nan: {df_concat_group1_group2}")
                break
            #df_concat_group1_group2 = df_concat_group1_group2.reset_index(drop=True) 
            result_df = result_df.reset_index(drop=True)
            if df_concat_group1_group2[(df_concat_group1_group2['pessoa']==1601) & (df_concat_group1_group2['atividade']=='A')].empty == False:
                         print("&&&&&&&&&&&existe&&&&&&&&&&&&&&&")                
            result_df = pd.concat([result_df, df_concat_group1_group2])
        else:    
            print("====================>nao entrou")    

    return result_df

In [581]:
## get dataset

# select only sensor data from smart watches
csv_gyro_dir = WORKDIR +"Data/Raw/phone/gyro"
csv_accel_dir = WORKDIR +"Data/Raw/phone/accel"

In [582]:
df_csv_gyro = combine_csv_data(csv_gyro_dir)

In [583]:
df_csv_gyro = df_csv_gyro.replace({';':''}, regex=True)

In [584]:
df_csv_gyro.columns = ['pessoa_gyro','atividade_gyro','tempo_gyro','giroscópio_x','giroscópio_Y','giroscópio_Z']

In [585]:
df_csv_gyro.head()

,pessoa_gyro,atividade_gyro,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,A,252207918580802,-0.853210,0.297226,0.8901825
1,1600,A,252207968934806,-0.875137,0.015472,0.16223145
2,1600,A,252208019288809,-0.720169,0.388489,-0.28401184
3,1600,A,252208069642813,-0.571640,1.227402,-0.2416687
4,1600,A,252208119996817,-0.380493,1.202835,-0.21313477

In [586]:
df_csv_gyro.tail()

,pessoa_gyro,atividade_gyro,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
3608630,1650,S,357733977635000,0.438889,0.171508,0.16937704
3608631,1650,S,357734017925000,0.444215,0.158724,0.19707392
3608632,1650,S,357734058325000,0.519849,0.037284,0.19600865
3608633,1650,S,357734098619000,0.545415,-0.086286,0.17896444
3608634,1650,S,357734138868000,0.471912,-0.201335,0.23222765

In [587]:
df_csv_gyro.shape

(3608635, 6)

In [588]:
df_csv_gyro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3608635 entries, 0 to 3608634
Data columns (total 6 columns):
 #   Column          Dtype
---  ------          -----
 0   pessoa_gyro     int64
 1   atividade_gyro  object
 2   tempo_gyro      int64
 3   giroscópio_x    float64
 4   giroscópio_Y    float64
 5   giroscópio_Z    object
dtypes: float64(2), int64(2), object(2)
memory usage: 165.2+ MB

In [589]:
''' condition1 = (df_csv_gyro['pessoa_gyro']== 1637) & (df_csv_gyro['atividade_gyro']=='C')
condition2 = (df_csv_gyro['pessoa_gyro']== 1638) & (df_csv_gyro['atividade_gyro']=='O')
condition3 = (df_csv_gyro['pessoa_gyro']== 1640) & (df_csv_gyro['atividade_gyro']=='C')
condition4 = (df_csv_gyro['pessoa_gyro']== 1640) & (df_csv_gyro['atividade_gyro']=='E')
condition5 = (df_csv_gyro['pessoa_gyro']== 1638) & (df_csv_gyro['atividade_gyro']=='H') '''

" condition1 = (df_csv_gyro['pessoa_gyro']== 1637) & (df_csv_gyro['atividade_gyro']=='C')\ncondition2 = (df_csv_gyro['pessoa_gyro']== 1638) & (df_csv_gyro['atividade_gyro']=='O')\ncondition3 = (df_csv_gyro['pessoa_gyro']== 1640) & (df_csv_gyro['atividade_gyro']=='C')\ncondition4 = (df_csv_gyro['pessoa_gyro']== 1640) & (df_csv_gyro['atividade_gyro']=='E')\ncondition5 = (df_csv_gyro['pessoa_gyro']== 1638) & (df_csv_gyro['atividade_gyro']=='H') "

In [590]:
df_csv_gyro.shape

(3608635, 6)

In [591]:
df_csv_gyro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3608635 entries, 0 to 3608634
Data columns (total 6 columns):
 #   Column          Dtype
---  ------          -----
 0   pessoa_gyro     int64
 1   atividade_gyro  object
 2   tempo_gyro      int64
 3   giroscópio_x    float64
 4   giroscópio_Y    float64
 5   giroscópio_Z    object
dtypes: float64(2), int64(2), object(2)
memory usage: 165.2+ MB

In [592]:
df_csv_accel = combine_csv_data(csv_accel_dir)

In [593]:
df_csv_accel = df_csv_accel.replace({';':''}, regex=True)

In [594]:
df_csv_accel.shape

(4804403, 6)

In [595]:
df_csv_accel.columns = ['pessoa','atividade','tempo_acelerômetro','acelerômetro_x','acelerômetro_Y','acelerômetro_Z']

In [596]:
df_csv_accel.head()

,pessoa,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z
0,1600,A,252207666810782,-0.364761,8.793503,1.0550842
1,1600,A,252207717164786,-0.879730,9.768784,1.0169983
2,1600,A,252207767518790,2.001495,11.109070,2.619156
3,1600,A,252207817872794,0.450623,12.651642,0.18455505
4,1600,A,252207868226798,-2.164352,13.928436,-4.4224854

In [597]:
df_csv_accel.tail()

,pessoa,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z
4804398,1650,S,357734078421000,-8.234077,-4.275110,-1.4394068
4804399,1650,S,357734098619000,-8.080796,-4.418811,-1.4154567
4804400,1650,S,357734118715000,-7.994575,-4.457131,-1.4418018
4804401,1650,S,357734138868000,-8.040081,-4.366121,-1.4968873
4804402,1650,S,357734158964000,-8.164622,-4.179309,-1.5304176

In [630]:
test1 = df_csv_accel[(df_csv_accel['pessoa']==1607) & (df_csv_accel['atividade']=='J')]

In [631]:
test1.head()

Empty DataFrame
Columns: [pessoa, atividade, tempo_acelerômetro, acelerômetro_x, acelerômetro_Y, acelerômetro_Z]
Index: []

In [600]:
#df_csv_accel.set_index(["pessoa_acelerômetro","atividade_acelerômetro","tempo_acelerômetro"],inplace=True)

In [601]:
#df_csv_accel.head()

In [602]:
''' condition_accel1 = (df_csv_accel['pessoa']== 1637) & (df_csv_accel['atividade']=='C')
condition_accel2 = (df_csv_accel['pessoa']== 1638) & (df_csv_accel['atividade']=='O')
condition_accel3 = (df_csv_accel['pessoa']== 1640) & (df_csv_accel['atividade']=='C')
condition_accel4 = (df_csv_accel['pessoa']== 1640) & (df_csv_accel['atividade']=='E')
condition_accel5 = (df_csv_accel['pessoa']== 1638) & (df_csv_accel['atividade']=='H') '''

" condition_accel1 = (df_csv_accel['pessoa']== 1637) & (df_csv_accel['atividade']=='C')\ncondition_accel2 = (df_csv_accel['pessoa']== 1638) & (df_csv_accel['atividade']=='O')\ncondition_accel3 = (df_csv_accel['pessoa']== 1640) & (df_csv_accel['atividade']=='C')\ncondition_accel4 = (df_csv_accel['pessoa']== 1640) & (df_csv_accel['atividade']=='E')\ncondition_accel5 = (df_csv_accel['pessoa']== 1638) & (df_csv_accel['atividade']=='H') "

In [603]:
df_csv_gyro.shape

(3608635, 6)

In [632]:
test2 = df_csv_gyro[(df_csv_gyro['pessoa_gyro']==1607) & (df_csv_gyro['atividade_gyro']=='j')]

In [633]:
test2.head()

Empty DataFrame
Columns: [pessoa_gyro, atividade_gyro, tempo_gyro, giroscópio_x, giroscópio_Y, giroscópio_Z]
Index: []

In [606]:
result_concatenation = custom_concat(df_csv_gyro.copy(),df_csv_accel.copy())

&&&&&&&&&&&existe&&&&&&&&&&&&&&&

In [607]:
result_concatenation.shape

(3608408, 12)

In [608]:
result_concatenation.head()

,pessoa,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,pessoa_gyro,atividade_gyro,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,A,252207666810782,-0.364761,8.793503,1.0550842,1600,A,252207918580802,-0.853210,0.297226,0.8901825
1,1600,A,252207717164786,-0.879730,9.768784,1.0169983,1600,A,252207968934806,-0.875137,0.015472,0.16223145
2,1600,A,252207767518790,2.001495,11.109070,2.619156,1600,A,252208019288809,-0.720169,0.388489,-0.28401184
3,1600,A,252207817872794,0.450623,12.651642,0.18455505,1600,A,252208069642813,-0.571640,1.227402,-0.2416687
4,1600,A,252207868226798,-2.164352,13.928436,-4.4224854,1600,A,252208119996817,-0.380493,1.202835,-0.21313477

In [609]:
result_concatenation = result_concatenation.reset_index(drop=True)

In [610]:
result_concatenation.tail()

,pessoa,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,pessoa_gyro,atividade_gyro,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
3608403,1650,S,357644019480000,-7.419771,-6.492898,-0.119750984,1650,S,357733977635000,0.438889,0.171508,0.16937704
3608404,1650,S,357644039687000,-7.644903,-7.391031,-0.64186525,1650,S,357734017925000,0.444215,0.158724,0.19707392
3608405,1650,S,357644059783000,-7.822134,-7.759863,-0.9915381,1650,S,357734058325000,0.519849,0.037284,0.19600865
3608406,1650,S,357644079967000,-7.125184,-6.569539,-1.1496094,1650,S,357734098619000,0.545415,-0.086286,0.17896444
3608407,1650,S,357644100063000,-6.159990,-5.316944,-1.1352394,1650,S,357734138868000,0.471912,-0.201335,0.23222765

In [611]:
test_diff_atividade = result_concatenation[result_concatenation['atividade']!=result_concatenation['atividade_gyro']]

In [612]:
print(test_diff_atividade.shape[0])

0

In [613]:
test_diff_pessoa = result_concatenation[result_concatenation['pessoa']!=result_concatenation['pessoa_gyro']]

In [614]:
print(len(test_diff_pessoa))

0

In [615]:
result_concatenation.columns

Index(['pessoa', 'atividade', 'tempo_acelerômetro', 'acelerômetro_x',
       'acelerômetro_Y', 'acelerômetro_Z', 'pessoa_gyro', 'atividade_gyro',
       'tempo_gyro', 'giroscópio_x', 'giroscópio_Y', 'giroscópio_Z'],
      dtype='object')

In [616]:
result_concatenation = result_concatenation[['pessoa', 'atividade', 'tempo_acelerômetro', 'acelerômetro_x',
       'acelerômetro_Y', 'acelerômetro_Z', 'tempo_gyro', 'giroscópio_x', 'giroscópio_Y', 'giroscópio_Z']]

In [617]:
result_concatenation.head()

,pessoa,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,A,252207666810782,-0.364761,8.793503,1.0550842,252207918580802,-0.853210,0.297226,0.8901825
1,1600,A,252207717164786,-0.879730,9.768784,1.0169983,252207968934806,-0.875137,0.015472,0.16223145
2,1600,A,252207767518790,2.001495,11.109070,2.619156,252208019288809,-0.720169,0.388489,-0.28401184
3,1600,A,252207817872794,0.450623,12.651642,0.18455505,252208069642813,-0.571640,1.227402,-0.2416687
4,1600,A,252207868226798,-2.164352,13.928436,-4.4224854,252208119996817,-0.380493,1.202835,-0.21313477

In [618]:
result_concatenation = result_concatenation.rename(columns={'pessoa':'pessoa_x'})

In [619]:
result_concatenation.head()

,pessoa_x,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,A,252207666810782,-0.364761,8.793503,1.0550842,252207918580802,-0.853210,0.297226,0.8901825
1,1600,A,252207717164786,-0.879730,9.768784,1.0169983,252207968934806,-0.875137,0.015472,0.16223145
2,1600,A,252207767518790,2.001495,11.109070,2.619156,252208019288809,-0.720169,0.388489,-0.28401184
3,1600,A,252207817872794,0.450623,12.651642,0.18455505,252208069642813,-0.571640,1.227402,-0.2416687
4,1600,A,252207868226798,-2.164352,13.928436,-4.4224854,252208119996817,-0.380493,1.202835,-0.21313477

In [628]:
test3 = result_concatenation[(result_concatenation['pessoa_x']==1607) & (result_concatenation['atividade']=='J')]

In [629]:
test3.head()

Empty DataFrame
Columns: [pessoa_x, atividade, tempo_acelerômetro, acelerômetro_x, acelerômetro_Y, acelerômetro_Z, tempo_gyro, giroscópio_x, giroscópio_Y, giroscópio_Z]
Index: []

In [622]:
# Define the mapping dictionary
mapping_dict = {'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6,'H':7,'I':8,'J':9,'K':10,'L':11,'M':12,'O':13,'P':14,'Q':15,'R':16,'S':17}

In [623]:
result_concatenation["atividade"] = result_concatenation["atividade"].replace(to_replace=mapping_dict)

In [624]:
test2.head()

,pessoa_gyro,atividade_gyro,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
64247,1601,A,265073308304101,-0.020240,-0.004261,-0.023435818
64248,1601,A,265073348330612,-1.213602,0.055394,-0.36964676
64249,1601,A,265073388368581,-2.417352,1.124387,-1.644502
64250,1601,A,265073428111445,-3.075152,1.530252,-1.6729978
64251,1601,A,265073468081082,0.011185,4.576909,-0.24367924

In [625]:
result_concatenation.head()

,pessoa_x,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,0,252207666810782,-0.364761,8.793503,1.0550842,252207918580802,-0.853210,0.297226,0.8901825
1,1600,0,252207717164786,-0.879730,9.768784,1.0169983,252207968934806,-0.875137,0.015472,0.16223145
2,1600,0,252207767518790,2.001495,11.109070,2.619156,252208019288809,-0.720169,0.388489,-0.28401184
3,1600,0,252207817872794,0.450623,12.651642,0.18455505,252208069642813,-0.571640,1.227402,-0.2416687
4,1600,0,252207868226798,-2.164352,13.928436,-4.4224854,252208119996817,-0.380493,1.202835,-0.21313477

In [626]:
result_concatenation.tail(50)

,pessoa_x,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
3608358,1650,17,357643112628000,-9.019644,-4.404441,-0.9532178,357732164299000,-0.400539,0.631702,0.29614353
3608359,1650,17,357643132724000,-8.497530,-4.255950,-0.7161109,357732204609000,-0.633832,0.159790,0.19813919
3608360,1650,17,357643152935000,-8.650811,-4.057163,-0.70174074,357732245045000,-0.693487,0.084156,0.20240025
3608361,1650,17,357643173031000,-8.959768,-4.169729,-0.48379397,357732285366000,-0.555003,0.166181,0.21837921
3608362,1650,17,357643193247000,-8.727451,-4.354145,-0.031135255,357732325601000,-0.387756,0.180030,0.20985709
3608363,1650,17,357643213343000,-8.444840,-4.397256,0.33769777,357732365904000,-0.227967,0.170442,0.17576863
3608364,1650,17,357643233519000,-8.073611,-4.430786,0.7041358,357732406269000,-0.124636,0.121440,0.165116
3608365,1650,17,357643253615000,-7.529942,-4.509822,0.9987232,357732446695000,-0.155529,0.020240,0.112918034
3608366,1650,17,357643273682000,-7.474856,-4.555327,1.1783496,357732487017000,-0.291882,0.011718,0.08948222
3608367,1650,17,357643293778000,-7.829319,-4.751719,1.2957057,357732527233000,-0.413323,0.052198,0.101200126
3608368,1650,17,357643313963000,-8.392149,-4.924161,1.2693604,357732567551000,-0.377104,0.052198,0.1438107
3608369,1650,17,357643334059000,-8.449629,-4.737349,1.1591895,357732607862000,-0.157659,0.021305,0.17896444
3608370,1650,17,357643354275000,-8.449629,-4.148174,0.92208254,357732648071000,0.042611,0.131028,0.11717909
3608371,1650,17,357643374371000,-8.356223,-3.884722,0.8334668,357732688411000,0.006392,0.115049,0.07350325
3608372,1650,17,357643394584000,-8.138277,-4.002078,0.77359134,357732728638000,-0.182160,0.117179,0.037284255
3608373,1650,17,357643414680000,-8.152647,-4.346960,0.6466553,357732768961000,-0.237554,0.149137,0.0063915867
3608374,1650,17,357643434886000,-8.061636,-4.790039,0.26345217,357732809273000,-0.126766,0.085221,-0.04580637
3608375,1650,17,357643454982000,-7.666458,-5.357659,-0.14849122,357732849508000,-0.006392,0.020240,-0.1768339
3608376,1650,17,357643475388000,-7.414981,-5.872588,-0.5891748,357732889818000,0.033023,0.112918,-0.010652645
3608377,1650,17,357643495484000,-7.292835,-6.071375,-1.0442286,357732930019000,0.177899,-0.028762,0.22264028
3608378,1650,17,357643515693000,-7.496411,-5.783972,-1.8441651,357732970331000,0.229032,-0.230097,0.25992453
3608379,1650,17,357643535789000,-7.587422,-5.283413,-2.7375073,357733010655000,-0.485761,-0.287621,0.36751625
3608380,1650,17,357643555932000,-6.950347,-4.876260,-4.0356083,357733050895000,-0.699879,-0.498544,0.21944448
3608381,1650,17,357643576028000,-6.789881,-4.787644,-4.4595265,357733091188000,-0.653007,-0.186421,0.053263225
3608382,1650,17,357643596244000,-7.798184,-4.696633,-1.8106349,357733131437000,-0.686030,-0.038350,0.11930962
3608383,1650,17,357643616340000,-8.301138,-4.902605,-0.5125342,357733171738000,-0.766990,0.064981,0.14061491
3608384,1650,17,357643636580000,-8.090376,-5.290598,-0.16286133,357733212036000,-0.955542,0.240750,0.026631612
3608385,1650,17,357643656676000,-7.666458,-5.463040,0.25147706,357733252256000,-1.313471,0.029827,-0.1768339
3608386,1650,17,357643676867000,-7.376660,-5.630691,0.4239185,357733292556000,-1.556351,0.045806,-0.49002165
3608387,1650,17,357643696963000,-7.089258,-5.937253,0.49337405,357733332809000,-1.282578,0.331297,-0.67324716
3608388,1650,17,357643717177000,-7.163504,-6.085745,0.27542725,357733373108000,-0.598679,-0.031958,-0.60933125
3608389,1650,17,357643737273000,-7.434141,-5.968389,-0.39278322,357733413402000,0.068177,-0.579504,-0.5454154
3608390,1650,17,357643757455000,-8.078402,-5.340894,-1.0538087,357733453677000,0.435693,-0.407996,-0.6860303
3608391,1650,17,357643777551000,-8.246053,-5.027146,-0.77359134,357733493968000,0.472977,0.223706,-0.83942837
3608392,1650,17,357643797753000,-8.372989,-4.928950,-0.0071850587,357733534229000,0.520914,1.204814,-0.716923
3608393,1650,17,357643817849000,-8.040081,-5.029541,0.33769777,357733574559000,0.723315,0.647681,-0.38775626
3608394,1650,17,357643838059000,-7.858059,-5.101392,-0.42152345,357733614842000,0.322775,-0.284426,-0.37390783
3608395,1650,17,357643858155000,-8.150251,-4.622388,-1.6405884,357733655089000,0.281230,0.283360,-0.3930826
3608396,1650,17,357643878365000,-7.860455,-4.263135,-1.5998731,357733695343000,0.494283,-0.190682,-0.12996227
3608397,1650,17,357643898461000,-6.849756,-4.655918,-0.84544194,357733735768000,0.529436,-0.115049,0.060720075
3608398,1650,17,357643918815000,-6.538404,-5.101392,-1.0298585,357733776060000,0.374973,-0.044741,0.084155895
3608399,1650,17,357643938911000,-6.945557,-5.458250,-1.9255958,357733816352000,0.348341,0.092678,0.15233281
3608400,1650,17,357643959089000,-7.134764,-5.733677,-2.2441335,357733856733000,0.601874,0.264186,0.18216023
3608401,1650,17,357643979185000,-7.139553,-5.728887,-1.0657837,357733897047000,0.759534,0.185356,0.23009712
3608402,1650,17,357643999384000,-7.120393,-5.879773,-0.028740235,357733937336000,0.598679,0.165116,0.20559604
3608403,1650,17,357644019480000,-7.419771,-6.492898,-0.119750984,357733977635000,0.438889,0.171508,0.16937704
3608404,1650,17,357644039687000,-7.644903,-7.391031,-0.64186525,357734017925000,0.444215,0.158724,0.19707392
3608405,1650,17,357644059783000,-7.822134,-7.759863,-0.9915381,357734058325000,0.519849,0.037284,0.19600865
3608406,1650,17,357644079967000,-7.125184,-6.569539,-1.1496094,357734098619000,0.545415,-0.086286,0.17896444
3608407,1650,17,357644100063000,-6.159990,-5.316944,-1.1352394,357734138868000,0.471912,-0.201335,0.23222765

In [627]:
result_concatenation.to_csv(WORKDIR + 'Data/processed/activity_recognition_data_phone_concat_by_comparacao_grupos.csv', index=False)