In [ ]:
# import modules
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import seaborn as sns
from pylab import rcParams
import matplotlib.pyplot as plt
from sklearn.model_selection import GroupShuffleSplit
from scipy import stats
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras import optimizers
from datetime import datetime
from kerastuner.tuners import RandomSearch
import tensorflow_addons as tfa
from keras.utils import to_categorical 
from keras.regularizers import l2
import os



r_seed = 42

from pathlib import Path
WORKDIR = str(Path.cwd().parent) + '/'  # raiz do repositório
np.random.seed(r_seed)
tf.random.set_seed(r_seed)
data_hora= datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
LOG_DIR = WORKDIR + "/logs/"+data_hora

In [ ]:
pd.set_option("display.precision", 9)

In [ ]:
date = datetime.now()
date = date.strftime("%d/%m/%Y_%H:%M")
arq = datetime.now()
arq = arq.strftime("%d_%m_%Y_%H_%M")

In [ ]:
def equalize_dataframe_sizes(df1, df2):
    """Equalizes the sizes of two DataFrames by dropping rows from the larger one.

    Args:
        df1 (pd.DataFrame): The first DataFrame.
        df2 (pd.DataFrame): The second DataFrame.

    Returns:
        tuple: A tuple containing the equalized DataFrames (df1, df2).

    Raises:
        ValueError: If both DataFrames have the same size.
    """

    if df1.shape[0] == df2.shape[0]:
        raise ValueError("Both DataFrames already have the same size.")

    larger_df, smaller_df = (df1, df2) if df1.shape[0] > df2.shape[0] else (df2, df1)

    # Drop rows from the larger DataFrame to match the smaller one
    larger_df = larger_df.iloc[: smaller_df.shape[0], :]

    return larger_df, smaller_df

# Example usage
#df1 = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': ['a', 'b', 'c', 'd', 'e']})
#df2 = pd.DataFrame({'A': [10, 20, 30], 'B': ['x', 'y', 'z']})

''' try:
    df1_equal, df2_equal = equalize_dataframe_sizes(df1.copy(), df2.copy())
    #print("Equalized DataFrames:")
    #print(df1_equal)
    #print(df2_equal)
except ValueError as e:
    print(e) '''

In [107]:
def custom_concat(df1, df2):
    """
    Concatenates two DataFrames with the same column names, considering specific conditions.

    Args:
        df1 (pd.DataFrame): The first DataFrame.
        df2 (pd.DataFrame): The second DataFrame.

    Returns:
        pd.DataFrame: The concatenated DataFrame.
    """

    result_df = pd.DataFrame()

    # Create groups based on unique combinations of X and Y values
    groups_df1 = df1.groupby(['pessoa_x_watch','atividade_watch'])
    groups_df2 = df2.groupby(['pessoa', 'ativ'])

    # Iterate over groups from both DataFrames simultaneously
    for (x, y), group1 in groups_df1:       
        group2 = groups_df2.get_group((x, y))     
        if group2 is not None:  # Check if corresponding group exists in df2
            if group1.shape[0] != group2.shape[0]:
                group1, group2 = equalize_dataframe_sizes(group1.copy(), group2.copy())
                
            group1 = group1.reset_index(drop=True) 
            group2 = group2.reset_index(drop=True)  
            df_concat_group1_group2 = pd.concat([group1, group2], axis=1)
            #print(df_concat_group1_group2)
            df_concat_group1_group2 = df_concat_group1_group2.dropna()            
            #print(df_concat_group1_group2)
            has_nan = df_concat_group1_group2.isnull().sum().sum() > 0
            if has_nan == True:
                print (f"**************************** Imprimindo concat co nan: {df_concat_group1_group2}")
                break
            df_concat_group1_group2 = df_concat_group1_group2.reset_index(drop=True) 
            result_df = result_df.reset_index(drop=True)
            result_df = pd.concat([result_df, df_concat_group1_group2])

    return result_df

In [108]:
df_watch = pd.read_csv("activity_recognition_data_watch_concat_by_comparacao_grupos.csv",dtype={"value":"float64"})

In [109]:
df_watch.head()

,pessoa_x,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904

In [110]:
df_watch.shape

(3441622, 10)

In [111]:
df_watch.atividade.value_counts().sort_index()

atividade
0     188925
1     184220
2     187622
3     191446
4     186899
5     190777
6     187144
7     194261
8     189816
9     193210
10    194315
11    197393
12    187927
13    187672
14    191241
15    201004
16    187171
17    200579
Name: count, dtype: int64

In [112]:
df_watch['atividade_watch'] = df_watch['atividade']

In [113]:
df_watch['pessoa_x_watch'] = df_watch['pessoa_x']

In [114]:
df_watch = df_watch.drop('pessoa_x',axis=1)

In [115]:
df_watch = df_watch.drop('atividade',axis=1)

In [116]:
df_watch.head()

,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z,atividade_watch,pessoa_x_watch
0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,0,1600
1,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,0,1600
2,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,0,1600
3,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,0,1600
4,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,0,1600

In [117]:
df_watch = df_watch.loc[~((df_watch['pessoa_x_watch'] == 1607) & (df_watch['atividade_watch'] == 9))]

In [118]:
#df_watch = df_watch[(df_watch['pessoa_x_watch'] != 1607) & (df_watch['atividade_watch'] != 9)]

In [119]:
df_watch.atividade_watch.value_counts().sort_index()

atividade_watch
0     188925
1     184220
2     187622
3     191446
4     186899
5     190777
6     187144
7     194261
8     189816
9     189608
10    194315
11    197393
12    187927
13    187672
14    191241
15    201004
16    187171
17    200579
Name: count, dtype: int64

In [120]:
df_watch = df_watch.loc[~((df_watch['pessoa_x_watch'] == 1609) & (df_watch['atividade_watch'] == 1))]

In [121]:
#df_watch = df_watch[(df_watch['pessoa_x_watch']!=1609) & (df_watch['atividade_watch']!=1) ]

In [122]:
df_watch = df_watch.loc[~((df_watch['pessoa_x_watch'] == 1616) & (df_watch['atividade_watch'] == 5))]

In [123]:
#df_watch = df_watch[(df_watch['pessoa_x_watch']!=1616) & (df_watch['atividade_watch']!=5) ]

In [124]:
df_watch = df_watch.loc[~((df_watch['pessoa_x_watch'] == 1641) & (df_watch['atividade_watch'] == 15))]

In [125]:
#df_watch = df_watch[(df_watch['pessoa_x_watch']!=1641) & (df_watch['atividade_watch']!=15) ]

In [126]:
df_watch = df_watch.loc[~((df_watch['pessoa_x_watch'] == 1644) & (df_watch['atividade_watch'] == 11))]

In [127]:
#df_watch = df_watch[(df_watch['pessoa_x_watch']!=1644) & (df_watch['atividade_watch']!=11) ]

In [128]:
df_watch = df_watch.loc[~((df_watch['pessoa_x_watch'] == 1643) & (df_watch['atividade_watch'] == 8))]

In [129]:
#df_watch = df_watch[(df_watch['pessoa_x_watch']!=1643) & (df_watch['atividade_watch']!=8) ]

In [130]:
df_watch.head()

,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z,atividade_watch,pessoa_x_watch
0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,0,1600
1,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,0,1600
2,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,0,1600
3,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,0,1600
4,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,0,1600

In [131]:
df_watch.shape

(3420018, 10)

In [132]:
df_watch.atividade_watch.value_counts().sort_index()

atividade_watch
0     188925
1     180617
2     187622
3     191446
4     186899
5     187174
6     187144
7     194261
8     186218
9     189608
10    194315
11    193794
12    187927
13    187672
14    191241
15    197405
16    187171
17    200579
Name: count, dtype: int64

In [133]:
df_watch.columns

Index(['tempo_acelerômetro', 'acelerômetro_x', 'acelerômetro_Y',
       'acelerômetro_Z', 'tempo_gyro', 'giroscópio_x', 'giroscópio_Y',
       'giroscópio_Z', 'atividade_watch', 'pessoa_x_watch'],
      dtype='object')

In [134]:
df_watch = df_watch [['pessoa_x_watch','atividade_watch', 'tempo_acelerômetro', 'acelerômetro_x', 'acelerômetro_Y',
       'acelerômetro_Z', 'tempo_gyro', 'giroscópio_x', 'giroscópio_Y',
       'giroscópio_Z']]

In [135]:
df_watch.head()

,pessoa_x_watch,atividade_watch,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904

In [136]:
df_watch.atividade_watch.value_counts()

atividade_watch
17    200579
15    197405
10    194315
7     194261
11    193794
3     191446
14    191241
9     189608
0     188925
12    187927
13    187672
2     187622
5     187174
16    187171
6     187144
4     186899
8     186218
1     180617
Name: count, dtype: int64

In [137]:
df_watch.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3420018 entries, 0 to 3441621
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   pessoa_x_watch      int64
 1   atividade_watch     int64
 2   tempo_acelerômetro  int64
 3   acelerômetro_x      float64
 4   acelerômetro_Y      float64
 5   acelerômetro_Z      float64
 6   tempo_gyro          int64
 7   giroscópio_x        float64
 8   giroscópio_Y        float64
 9   giroscópio_Z        float64
dtypes: float64(6), int64(4)
memory usage: 287.0 MB

In [138]:
df_phone = pd.read_csv("activity_recognition_data_phone_concat_by_comparacao_grupos.csv",dtype={"value":"float64"})

In [139]:
df_phone.shape

(3608408, 10)

In [140]:
df_phone.head()

,pessoa_x,atividade,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,0,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [141]:
df_phone['atividade_phone'] = df_phone['atividade']

In [142]:
df_phone['pessoa_x_phone'] = df_phone['pessoa_x']

In [143]:
df_phone = df_phone.drop('pessoa_x',axis=1)

In [144]:
df_phone = df_phone.drop('atividade',axis=1)

In [145]:
df_phone.columns

Index(['tempo_acelerômetro', 'acelerômetro_x', 'acelerômetro_Y',
       'acelerômetro_Z', 'tempo_gyro', 'giroscópio_x', 'giroscópio_Y',
       'giroscópio_Z', 'atividade_phone', 'pessoa_x_phone'],
      dtype='object')

In [146]:
df_phone = df_phone [['pessoa_x_phone','atividade_phone','tempo_acelerômetro', 'acelerômetro_x', 'acelerômetro_Y',
       'acelerômetro_Z', 'tempo_gyro', 'giroscópio_x', 'giroscópio_Y',
       'giroscópio_Z']]

In [147]:
df_phone.columns= ['pessoa','ativ','tempo_acel', 'acel_x_', 'acel_Y',
       'acel_Z', 'temp_gyro', 'giro_x', 'giro_Y_',
       'giro_Z']

In [148]:
df_phone.head()

,pessoa,ativ,tempo_acel,acel_x_,acel_Y,acel_Z,temp_gyro,giro_x,giro_Y_,giro_Z
0,1600,0,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [149]:
df_phone.shape

(3608408, 10)

In [150]:
df_phone.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3608408 entries, 0 to 3608407
Data columns (total 10 columns):
 #   Column      Dtype
---  ------      -----
 0   pessoa      int64
 1   ativ        int64
 2   tempo_acel  int64
 3   acel_x_     float64
 4   acel_Y      float64
 5   acel_Z      float64
 6   temp_gyro   int64
 7   giro_x      float64
 8   giro_Y_     float64
 9   giro_Z      float64
dtypes: float64(6), int64(4)
memory usage: 275.3 MB

In [151]:
df_phone.reset_index(drop = True,inplace=True)

In [152]:
df_phone.ativ.value_counts()

ativ
0     203919
12    202623
6     202620
7     202407
10    202395
3     202369
4     202350
16    202329
14    202329
17    202320
1     200251
13    198755
11    197914
8     197905
15    197894
2     197855
9     197841
5     194332
Name: count, dtype: int64

In [153]:
df_phone.head()

,pessoa,ativ,tempo_acel,acel_x_,acel_Y,acel_Z,temp_gyro,giro_x,giro_Y_,giro_Z
0,1600,0,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [154]:
df_watch.reset_index(drop = True,inplace=True)

In [155]:
df_watch.shape

(3420018, 10)

In [156]:
df_watch.head()

,pessoa_x_watch,atividade_watch,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904

In [157]:
result_concatenation = custom_concat(df_watch.copy(),df_phone.copy())

In [158]:
result_concatenation.shape

(3231373, 20)

In [159]:
result_concatenation.head()

,pessoa_x_watch,atividade_watch,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z,pessoa,ativ,tempo_acel,acel_x_,acel_Y,acel_Z,temp_gyro,giro_x,giro_Y_,giro_Z
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,1600,0,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,1600,0,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,1600,0,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,1600,0,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,1600,0,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [160]:
result_concatenation = result_concatenation.reset_index(drop=True)

In [161]:
result_concatenation.atividade_watch.value_counts().sort_index()

atividade_watch
0     180867
1     173496
2     174572
3     180932
4     176419
5     180051
6     182720
7     185286
8     176429
9     177335
10    180937
11    179122
12    180587
13    173691
14    183553
15    180011
16    182685
17    182680
Name: count, dtype: int64

In [162]:
result_concatenation.tail()

,pessoa_x_watch,atividade_watch,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z,pessoa,ativ,tempo_acel,acel_x_,acel_Y,acel_Z,temp_gyro,giro_x,giro_Y_,giro_Z
3231368,1650,17,2426184321449912,4.7689505,-5.4014688,7.5842323,2426184371437252,-2.8560646,2.0571015,0.85393304,1650,17,357626608042000,-7.2760696,-5.3025737,-1.8297950,357699155079000,0.041545313,-0.165116000,-0.177899170
3231369,1650,17,2426184371437252,2.1377227,-7.2114854,8.0654670,2426184421424592,-2.9114583,1.8174170,1.28110410,1650,17,357626628138000,-7.1443434,-5.4606447,-2.0190015,357699195384000,0.214118150,-0.291882460,-0.116113830
3231370,1650,17,2426184421424592,1.4865000,-13.3023340,5.3552310,2426184471411932,-3.0158541,1.5500356,2.05768180,1650,17,357626648248000,-7.1635036,-5.5348900,-2.1842580,357699235690000,0.517718550,-0.118244360,-0.103330650
3231371,1650,17,2426184471411932,4.0171714,-13.1467110,5.1182046,2426184521399272,-3.2182543,1.5958420,3.01855040,1650,17,357626668344000,-7.3143900,-5.6259010,-2.0980372,357699275996000,0.394147840,0.034088463,-0.071372720
3231372,1650,17,2426184521399272,4.4122143,-15.3182530,3.3704374,2426184571385262,-2.4555252,0.8661359,3.35410860,1650,17,357626688550000,-7.2497244,-5.9324636,-1.5926881,357699316371000,0.246076090,0.169377040,0.053263225

In [163]:
result_concatenation.shape

(3231373, 20)

In [164]:
test_diff_atividade = result_concatenation[result_concatenation['atividade_watch']!=result_concatenation['ativ']]

In [165]:
print(test_diff_atividade.shape[0])

0

In [166]:
test_diff_pessoa = result_concatenation[result_concatenation['pessoa_x_watch']!=result_concatenation['pessoa']]

In [167]:
print(len(test_diff_pessoa))

0

In [168]:
result_concatenation.columns

Index(['pessoa_x_watch', 'atividade_watch', 'tempo_acelerômetro',
       'acelerômetro_x', 'acelerômetro_Y', 'acelerômetro_Z', 'tempo_gyro',
       'giroscópio_x', 'giroscópio_Y', 'giroscópio_Z', 'pessoa', 'ativ',
       'tempo_acel', 'acel_x_', 'acel_Y', 'acel_Z', 'temp_gyro', 'giro_x',
       'giro_Y_', 'giro_Z'],
      dtype='object')

In [169]:
result_concatenation = result_concatenation[['pessoa_x_watch', 'atividade_watch', 'tempo_acelerômetro',
       'acelerômetro_x', 'acelerômetro_Y', 'acelerômetro_Z', 'tempo_gyro',
       'giroscópio_x', 'giroscópio_Y', 'giroscópio_Z','tempo_acel', 'acel_x_', 'acel_Y', 'acel_Z', 'temp_gyro', 
       'giro_x','giro_Y_', 'giro_Z']]

In [170]:
result_concatenation.head()

,pessoa_x_watch,atividade_watch,tempo_acelerômetro,acelerômetro_x,acelerômetro_Y,acelerômetro_Z,tempo_gyro,giroscópio_x,giroscópio_Y,giroscópio_Z,tempo_acel,acel_x_,acel_Y,acel_Z,temp_gyro,giro_x,giro_Y_,giro_Z
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [171]:
result_concatenation.head().columns

Index(['pessoa_x_watch', 'atividade_watch', 'tempo_acelerômetro',
       'acelerômetro_x', 'acelerômetro_Y', 'acelerômetro_Z', 'tempo_gyro',
       'giroscópio_x', 'giroscópio_Y', 'giroscópio_Z', 'tempo_acel', 'acel_x_',
       'acel_Y', 'acel_Z', 'temp_gyro', 'giro_x', 'giro_Y_', 'giro_Z'],
      dtype='object')

In [172]:
result_concatenation.columns = ['pessoa_x', 'atividade', 'tempo_acelerômetro_watch',
       'acelerômetro_x_watch', 'acelerômetro_Y_watch', 'acelerômetro_Z_watch', 'tempo_gyro_watch',
       'giroscópio_x_watch', 'giroscópio_Y_watch', 'giroscópio_Z_watch', 'tempo_acelerômetro_phone', 'acelerômetro_x_phone',
       'acelerômetro_Y_phone', 'acelerômetro_Z_phone', 'tempo_giroscópio_phone',
         'giroscópio_x_phone', 'giroscópio_Y_phone', 'giroscópio_Z_phone']

In [173]:
result_concatenation.head()

,pessoa_x,atividade,tempo_acelerômetro_watch,acelerômetro_x_watch,acelerômetro_Y_watch,acelerômetro_Z_watch,tempo_gyro_watch,giroscópio_x_watch,giroscópio_Y_watch,giroscópio_Z_watch,tempo_acelerômetro_phone,acelerômetro_x_phone,acelerômetro_Y_phone,acelerômetro_Z_phone,tempo_giroscópio_phone,giroscópio_x_phone,giroscópio_Y_phone,giroscópio_Z_phone
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [174]:
result_concatenation.head()

,pessoa_x,atividade,tempo_acelerômetro_watch,acelerômetro_x_watch,acelerômetro_Y_watch,acelerômetro_Z_watch,tempo_gyro_watch,giroscópio_x_watch,giroscópio_Y_watch,giroscópio_Z_watch,tempo_acelerômetro_phone,acelerômetro_x_phone,acelerômetro_Y_phone,acelerômetro_Z_phone,tempo_giroscópio_phone,giroscópio_x_phone,giroscópio_Y_phone,giroscópio_Z_phone
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [175]:
# Define the mapping dictionary
mapping_dict = {'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6,'H':7,'I':8,'J':9,'K':10,'L':11,'M':12,'O':13,'P':14,'Q':15,'R':16,'S':17}

In [176]:
result_concatenation["atividade"] = result_concatenation["atividade"].replace(to_replace=mapping_dict)

In [177]:
result_concatenation.head()

,pessoa_x,atividade,tempo_acelerômetro_watch,acelerômetro_x_watch,acelerômetro_Y_watch,acelerômetro_Z_watch,tempo_gyro_watch,giroscópio_x_watch,giroscópio_Y_watch,giroscópio_Z_watch,tempo_acelerômetro_phone,acelerômetro_x_phone,acelerômetro_Y_phone,acelerômetro_Z_phone,tempo_giroscópio_phone,giroscópio_x_phone,giroscópio_Y_phone,giroscópio_Z_phone
0,1600,0,90426708196641,7.0916250,-0.59166710,8.1955020,90426757696641,0.314944100,-1.02227650,-0.309961600,252207666810782,-0.36476135,8.793503,1.05508420,252207918580802,-0.85321045,0.297225950,0.89018250
1,1600,0,90426757696641,4.9727570,-0.15831658,6.6967316,90426807196641,0.387382100,-0.61854124,-0.048971802,252207717164786,-0.87973020,9.768784,1.01699830,252207968934806,-0.87513730,0.015472412,0.16223145
2,1600,0,90426807196641,3.2537200,-0.19183542,6.1077580,90426856696641,0.070998540,-0.20947972,-0.195978300,252207767518790,2.00149540,11.109070,2.61915600,252208019288809,-0.72016907,0.388488770,-0.28401184
3,1600,0,90426856696641,2.8012160,-0.15592238,5.9976250,90426906196641,0.037975345,0.25497556,-0.156563500,252207817872794,0.45062256,12.651642,0.18455505,252208069642813,-0.57164000,1.227401700,-0.24166870
4,1600,0,90426906196641,3.7708676,-1.05135380,7.7310270,90426955696641,0.073129070,0.71943086,-0.001034904,252207868226798,-2.16435240,13.928436,-4.42248540,252208119996817,-0.38049316,1.202835100,-0.21313477

In [178]:
result_concatenation.shape

(3231373, 18)

In [179]:
result_concatenation.tail(50)

,pessoa_x,atividade,tempo_acelerômetro_watch,acelerômetro_x_watch,acelerômetro_Y_watch,acelerômetro_Z_watch,tempo_gyro_watch,giroscópio_x_watch,giroscópio_Y_watch,giroscópio_Z_watch,tempo_acelerômetro_phone,acelerômetro_x_phone,acelerômetro_Y_phone,acelerômetro_Z_phone,tempo_giroscópio_phone,giroscópio_x_phone,giroscópio_Y_phone,giroscópio_Z_phone
3231323,1650,17,2426182071909922,2.68120670,-4.80291840,8.1588410,2426182121897632,-1.969764500,1.562818800,-0.003604855,357625701021000,-6.6198344,-6.3372220,-2.0309765,357697341426000,-0.220509740,0.009587380,-0.059654810
3231324,1650,17,2426182121897632,0.72035545,-4.22591540,12.9472450,2426182171885342,1.064108600,1.739652800,0.359650300,357625721220000,-6.9168167,-5.9324636,-2.1459377,357697381707000,-0.191747600,0.181094960,-0.054328486
3231325,1650,17,2426182171885342,0.26785132,-10.12044050,10.8307700,2426182221873052,4.321687000,2.470424200,-0.798292100,357625741316000,-7.1970340,-5.5444703,-2.2249732,357697422007000,-0.006391587,0.147006500,0.029827405
3231326,1650,17,2426182221873052,-1.84144040,3.92155270,7.8021050,2426182271860762,1.949343300,2.141257300,-1.457690800,357625761598000,-7.5467067,-5.2690430,-2.2273684,357697462212000,0.149137020,0.019174760,0.084155895
3231327,1650,17,2426182271860762,-3.95552040,6.04999830,6.0016650,2426182321848472,1.746943100,2.089059400,-1.445972900,357625781694000,-7.7311234,-4.8930250,-2.1076174,357697502480000,0.155528600,-0.095873800,0.098004326
3231328,1650,17,2426182321848472,-8.68406900,-0.68249714,5.1684830,2426182371836182,1.905667500,1.122864600,-0.977256540,357625801924000,-7.7957890,-4.4667115,-2.0142114,357697542846000,0.005326322,-0.089482220,0.062850600
3231329,1650,17,2426182371836182,-7.83652160,0.83303255,4.8404775,2426182421823892,-0.828866240,0.741499960,0.061376274,357625822020000,-7.7814190,-4.1194340,-1.9184108,357697583164000,-0.172572840,-0.043675844,0.008522116
3231330,1650,17,2426182421823892,-9.03601600,-0.97219550,4.0671500,2426182471816332,0.509105860,0.121516040,-0.069651246,357625842216000,-7.8317140,-4.0403980,-1.7172291,357697623461000,-0.216248690,-0.079894830,-0.012783173
3231331,1650,17,2426182471816332,-8.24353600,-0.31857845,6.3033347,2426182521808772,0.791400900,-0.638017500,-0.512801230,357625862312000,-7.7311234,-4.2870850,-1.4394068,357697663616000,-0.133158060,-0.117179090,-0.027696876
3231332,1650,17,2426182521808772,-6.04565860,2.34616800,6.8923080,2426182571801212,0.905384240,-1.036426400,-0.518127560,357625882480000,-7.6616680,-4.6295730,-1.3244458,357697703923000,-0.035153728,-0.116113830,-0.041545313
3231333,1650,17,2426182571801212,1.20637830,0.42841247,13.4141140,2426182621793652,0.395122560,1.837657100,0.276559680,357625902576000,-7.7047780,-5.0487013,-1.4346168,357697744230000,0.020240024,-0.027696876,-0.029827405
3231334,1650,17,2426182621793652,4.37869550,1.13949040,15.9687270,2426182671786092,-0.468806900,3.125561700,0.569507400,357625922794000,-7.7239385,-5.4510646,-1.6645386,357697784501000,0.024501082,0.028762140,-0.028762140
3231335,1650,17,2426182671786092,-2.47590370,4.97978970,8.1157460,2426182721778532,-0.820344150,2.542862200,0.056049954,357625942890000,-7.5562870,-5.6474560,-1.9399658,357697824835000,0.024501082,-0.015978966,-0.047936900
3231336,1650,17,2426182721778532,-7.97299100,6.16731400,4.1605240,2426182771770972,0.750920900,1.321003800,-0.437167470,357625963099000,-7.1443434,-5.6690116,-2.1914430,357697865133000,0.000000000,-0.084155895,-0.039414786
3231337,1650,17,2426182771770972,-7.11107830,2.86331560,4.4406457,2426182821763412,-0.616878600,0.531642850,-0.887774350,357625983195000,-6.9742970,-5.7025420,-2.5027955,357697905443000,-0.101200126,-0.079894830,-0.049002163
3231338,1650,17,2426182821763412,-6.09354260,3.83536150,2.3505075,2426182871755852,-0.108747520,0.190758230,-1.025193500,357626003398000,-6.9623220,-5.7408620,-2.8285182,357697945750000,-0.172572840,-0.045806370,-0.042610580
3231339,1650,17,2426182871755852,-5.33458100,2.60234760,1.2419921,2426182921748292,-0.231252920,-1.261197200,-1.162612600,357626023494000,-6.8761015,-5.6163210,-2.9817994,357697986087000,-0.122505410,-0.056459017,-0.021305290
3231340,1650,17,2426182921748292,-4.86531730,2.37250420,-0.7092823,2426182971740732,-0.267471900,-2.644975700,-1.622806800,357626043699000,-6.9958525,-5.4079540,-2.8069630,357698026413000,-0.035153728,-0.084155895,-0.007456851
3231341,1650,17,2426182971740732,-3.77834960,1.34299760,2.2930467,2426183021733172,2.445756700,-3.221283700,-1.944516700,357626063795000,-7.3455253,-5.2905984,-2.5626710,357698066728000,-0.002130529,-0.039414786,-0.012783173
3231342,1650,17,2426183021733172,-1.97790990,2.13308400,5.2283380,2426183071725612,0.936276900,-4.170434500,-2.037194700,357626084029000,-7.6113725,-5.2115626,-2.4165747,357698107126000,0.006391587,0.015978966,-0.053263225
3231343,1650,17,2426183071725612,0.11941081,0.69656307,6.8300590,2426183121718052,-1.554311400,-4.255655300,-2.098980000,357626104125000,-7.7383084,-5.0894165,-2.2537134,357698147457000,0.063915860,0.019174760,-0.088416950
3231344,1650,17,2426183121718052,2.89429070,1.93675960,11.5729720,2426183171710492,-5.747192000,-3.756046500,-2.059565300,357626124343000,-7.7383084,-5.0295410,-1.9040406,357698187763000,0.153398080,-0.035153728,-0.079894830
3231345,1650,17,2426183171710492,6.60530330,-0.32815528,10.0694140,2426183221702932,-6.360784500,-0.218303310,1.368455800,357626144439000,-7.7454934,-5.0654664,-1.5040723,357698228070000,0.175768630,-0.095873800,-0.098004326
3231346,1650,17,2426183221702932,7.62523300,-8.32957700,8.4724820,2426183271695372,-4.550900000,0.116189726,2.593510000,357626164602000,-7.7335186,-5.2355127,-1.1567944,357698268379000,0.101200126,-0.150202290,-0.122505410
3231347,1650,17,2426183271695372,3.10019180,-11.49710700,7.5291657,2426183321687812,-1.317822700,-1.101407500,0.964720500,357626184698000,-7.6449027,-5.4534597,-0.9508228,357698308826000,0.037284255,-0.155528600,-0.170442310
3231348,1650,17,2426183321687812,1.46016370,-8.10452300,3.4542346,2426183371680252,0.432406800,-1.629778600,-0.315727320,357626204881000,-7.4269557,-5.6282964,-0.9867481,357698349124000,0.018109497,-0.210922360,-0.246076090
3231349,1650,17,2426183371680252,-0.67306995,-8.16677200,3.7535098,2426183421672692,-0.130052800,-2.379724700,-1.255290500,357626224977000,-7.2545147,-5.6857767,-1.0538087,357698389396000,0.013848438,-0.227966590,-0.289751950
3231350,1650,17,2426183421672692,-0.12719196,-6.40224500,5.4988830,2426183471665132,-0.454958470,-2.742980000,-2.274748600,357626245186000,-7.3622904,-5.6522465,-1.0657837,357698429705000,0.014913702,-0.233292920,-0.322775130
3231351,1650,17,2426183471665132,1.50325940,-8.46365300,3.8588545,2426183521652472,1.981301300,-2.342440600,-2.917103000,357626265282000,-7.5035963,-5.4654350,-1.1304493,357698470014000,0.047936900,-0.221575000,-0.292947740
3231352,1650,17,2426183521652472,4.03871900,-9.29444000,7.9146323,2426183571639812,4.024478400,-1.847092600,-3.000193600,357626285542000,-7.6305327,-5.1756372,-1.2669654,357698510321000,0.057524280,-0.240749760,-0.291882460
3231353,1650,17,2426183571639812,4.59656800,-8.32957700,8.9058310,2426183621627152,2.095284700,-1.407138500,-1.419341300,357626305638000,-7.7694435,-5.0008010,-1.2933106,357698550623000,-0.007456851,-0.378168880,-0.438888970
3231354,1650,17,2426183621627152,6.42094950,-4.08705200,10.7685200,2426183671614492,-1.126075000,-1.342157200,-0.359403160,357626325877000,-7.9179350,-4.9073954,-1.3819263,357698590925000,-0.137419120,-0.351537260,-0.524110140
3231355,1650,17,2426183671614492,4.82162300,-6.57702160,10.9983640,2426183721601832,0.827619900,-0.355722430,-0.390295830,357626345973000,-8.0568460,-4.8139896,-1.5112574,357698631225000,-0.328101460,-0.034088463,-0.464455300
3231356,1650,17,2426183721601832,5.96365740,-3.76383470,11.1300450,2426183771589172,-1.033397100,0.756413640,-0.634241400,357626366179000,-8.1334870,-4.6870530,-1.5304176,357698671454000,0.137419120,-0.404800500,-0.482564800
3231357,1650,17,2426183771589172,6.11449200,-1.82453130,10.2968630,2426183821576512,-1.716231600,0.806481060,-1.089109300,357626386275000,-8.1742020,-4.5649076,-1.4226416,357698711744000,0.630636600,-0.836232600,-0.521979600
3231358,1650,17,2426183821576512,5.27652100,-3.42625240,7.3591776,2426183871563852,-1.999591800,0.245086710,-1.017736600,357626406475000,-8.0784020,-4.4954520,-1.2214600,357698752055000,0.649811300,-0.670051340,-0.401604700
3231359,1650,17,2426183871563852,5.73141960,-2.65292500,5.3025584,2426183921551192,-3.103206000,0.139625530,-0.331706300,357626426571000,-7.8748245,-4.4930570,-1.2334352,357698792328000,0.659398700,-0.343015160,-0.298274040
3231360,1650,17,2426183921551192,7.86465300,-3.95058250,6.6241574,2426183971538532,-2.585487400,0.470922770,-0.321053650,357626446790000,-7.8077640,-4.7110040,-1.5280225,357698832631000,0.714792430,-0.451672140,-0.299339320
3231361,1650,17,2426183971538532,8.31476300,-7.87228500,5.3360770,2426184021525872,0.010562097,0.282370980,-0.389230580,357626466886000,-7.7646537,-4.9241605,-1.7555494,357698872935000,0.708400850,-0.796817840,-0.276968750
3231362,1650,17,2426184021525872,7.09372040,-4.29295350,6.8994910,2426184071513212,-0.046962183,0.158800300,-0.441428540,357626487103000,-7.7670490,-4.9289503,-1.8441651,357698913234000,0.676442900,-0.798948350,-0.184290750
3231363,1650,17,2426184071513212,8.64995200,-3.43582920,5.8244944,2426184121500552,0.614567040,-0.042534675,-0.459538040,357626507199000,-7.8796150,-4.9385304,-1.7699195,357698953542000,0.735032500,-0.744619850,-0.233292920
3231364,1650,17,2426184121500552,10.08407800,-3.47413640,4.0791210,2426184171487892,3.075327900,-0.259848620,-0.243289350,357626527439000,-7.9993660,-4.9864306,-1.6860938,357698993850000,1.024784400,-1.405083800,-0.403735220
3231365,1650,17,2426184171487892,10.25885500,-3.85242000,3.3967736,2426184221475232,2.056935000,0.486901730,0.480025200,357626547535000,-7.8844047,-4.9672710,-1.6549586,357699034193000,1.339037400,-1.994175100,-0.268446650
3231366,1650,17,2426184221475232,9.76565000,-1.04881000,5.4581814,2426184271462572,-2.259516500,0.953487600,0.987091060,357626567740000,-7.6951980,-4.9433208,-1.6645386,357699074477000,1.242098300,-1.439172300,-0.079894830
3231367,1650,17,2426184271462572,8.09689000,-2.55476280,6.5092360,2426184321449912,-2.291474300,1.720477900,1.023310100,357626587836000,-7.4940166,-5.0918117,-1.7172291,357699114776000,0.606135500,-0.544350150,-0.156593870
3231368,1650,17,2426184321449912,4.76895050,-5.40146880,7.5842323,2426184371437252,-2.856064600,2.057101500,0.853933040,357626608042000,-7.2760696,-5.3025737,-1.8297950,357699155079000,0.041545313,-0.165116000,-0.177899170
3231369,1650,17,2426184371437252,2.13772270,-7.21148540,8.0654670,2426184421424592,-2.911458300,1.817417000,1.281104100,357626628138000,-7.1443434,-5.4606447,-2.0190015,357699195384000,0.214118150,-0.291882460,-0.116113830
3231370,1650,17,2426184421424592,1.48650000,-13.30233400,5.3552310,2426184471411932,-3.015854100,1.550035600,2.057681800,357626648248000,-7.1635036,-5.5348900,-2.1842580,357699235690000,0.517718550,-0.118244360,-0.103330650
3231371,1650,17,2426184471411932,4.01717140,-13.14671100,5.1182046,2426184521399272,-3.218254300,1.595842000,3.018550400,357626668344000,-7.3143900,-5.6259010,-2.0980372,357699275996000,0.394147840,0.034088463,-0.071372720
3231372,1650,17,2426184521399272,4.41221430,-15.31825300,3.3704374,2426184571385262,-2.455525200,0.866135900,3.354108600,357626688550000,-7.2497244,-5.9324636,-1.5926881,357699316371000,0.246076090,0.169377040,0.053263225

In [180]:
result_concatenation.to_csv(WORKDIR + 'Data/processed/activity_recognition_data_WATCH_PHONE_concat_by_comparacao_grupos.csv', index=False)